Add FN_StudentUpcoming_installment
Ahmed-cmd-web/DATABASED pull request #143
Opened 2023-11-29 14:31 UTC by MostafaVT

add: test cases
#97

2023-11-30 04:22 UTC, Ahmed-cmd-web requested changes
Change this before merging:

In debug.sql,slot takes time as int not varchar
INSERT INTO Slot (day, time, location, course_id, instructor_id)
VALUES ('Monday', 'First', 'Room 101', 1, 1);

2023-11-30 04:22 UTC, Ahmed-cmd-web approved these changes

2023-12-03 12:09 UTC, AhmedV100 approved these changes

2023-12-03 12:09 UTC, A-HO7 approved these changes

2023-12-03 12:09 UTC, merged